--
-- PostgreSQL database dump
--

\restrict 4PHWJWaB9AhX9ycsKHRehZy2cPXaBBaeBNNSkeSRb4lurwYRYluKCsRhQwFgvNk

-- Dumped from database version 18.6
-- Dumped by pg_dump version 18.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: appointment; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.appointment (
    appointment_id integer NOT NULL,
    appointment_dt timestamp with time zone NOT NULL,
    patient_id integer NOT NULL,
    doctor_id integer NOT NULL,
    status text DEFAULT 'scheduled'::text NOT NULL,
    CONSTRAINT appointment_status_check CHECK ((status = ANY (ARRAY['scheduled'::text, 'completed'::text, 'cancelled'::text, 'no_show'::text])))
);


--
-- Name: appointment_appointment_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.appointment ALTER COLUMN appointment_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.appointment_appointment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bill; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bill (
    bill_id integer NOT NULL,
    visit_id integer NOT NULL,
    amount numeric(10,2) NOT NULL,
    bill_date date NOT NULL,
    status text DEFAULT 'unpaid'::text NOT NULL,
    CONSTRAINT bill_amount_check CHECK (((amount >= 0.01) AND (amount <= 99999999.99))),
    CONSTRAINT bill_status_check CHECK ((status = ANY (ARRAY['unpaid'::text, 'partially_paid'::text, 'paid'::text])))
);


--
-- Name: bill_bill_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.bill ALTER COLUMN bill_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bill_bill_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: doctor; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.doctor (
    doctor_id integer NOT NULL,
    first_name text NOT NULL,
    last_name text NOT NULL,
    specialty text NOT NULL,
    phone text,
    email text NOT NULL,
    CONSTRAINT doctor_first_name_check CHECK ((btrim(first_name) <> ''::text)),
    CONSTRAINT doctor_last_name_check CHECK ((btrim(last_name) <> ''::text)),
    CONSTRAINT doctor_specialty_check CHECK ((btrim(specialty) <> ''::text))
);


--
-- Name: doctor_doctor_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.doctor ALTER COLUMN doctor_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.doctor_doctor_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: visit; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.visit (
    visit_id integer NOT NULL,
    appointment_id integer NOT NULL,
    visit_date date NOT NULL,
    diagnosis text NOT NULL,
    treatment text NOT NULL,
    CONSTRAINT visit_diagnosis_check CHECK ((btrim(diagnosis) <> ''::text)),
    CONSTRAINT visit_treatment_check CHECK ((btrim(treatment) <> ''::text))
);


--
-- Name: medical_history; Type: VIEW; Schema: public; Owner: -
--

CREATE VIEW public.medical_history AS
 SELECT a.patient_id,
    v.visit_id,
    a.doctor_id,
    v.diagnosis,
    v.treatment,
    v.visit_date
   FROM (public.visit v
     JOIN public.appointment a ON ((a.appointment_id = v.appointment_id)));


--
-- Name: VIEW medical_history; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON VIEW public.medical_history IS 'Patient medical history derived from visits and appointments; includes doctor_id.';


--
-- Name: patient; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.patient (
    patient_id integer NOT NULL,
    first_name text NOT NULL,
    last_name text NOT NULL,
    email text,
    gender text,
    phone text,
    CONSTRAINT patient_first_name_check CHECK ((btrim(first_name) <> ''::text)),
    CONSTRAINT patient_last_name_check CHECK ((btrim(last_name) <> ''::text))
);


--
-- Name: patient_patient_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.patient ALTER COLUMN patient_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.patient_patient_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payment; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.payment (
    payment_id integer NOT NULL,
    bill_id integer NOT NULL,
    amount_paid numeric(10,2) NOT NULL,
    payment_date date NOT NULL,
    payment_method text NOT NULL,
    CONSTRAINT payment_amount_check CHECK (((amount_paid >= 0.01) AND (amount_paid <= 99999999.99))),
    CONSTRAINT payment_method_check CHECK ((payment_method = ANY (ARRAY['cash'::text, 'debit_card'::text, 'credit_card'::text, 'e_transfer'::text])))
);


--
-- Name: payment_payment_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.payment ALTER COLUMN payment_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payment_payment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: visit_visit_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.visit ALTER COLUMN visit_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.visit_visit_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: appointment; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.appointment (appointment_id, appointment_dt, patient_id, doctor_id, status) FROM stdin;
1	2026-07-01 09:15:00-06	7	7	completed
2	2026-07-02 09:15:00-06	12	5	completed
3	2026-07-03 09:15:00-06	4	4	completed
4	2026-07-06 09:15:00-06	10	3	completed
5	2026-07-07 09:15:00-06	21	5	completed
6	2026-07-08 09:15:00-06	15	15	completed
7	2026-07-09 09:15:00-06	12	5	completed
8	2026-07-10 09:15:00-06	17	10	completed
9	2026-07-13 09:15:00-06	8	8	completed
10	2026-07-14 09:15:00-06	16	16	completed
11	2026-07-15 09:15:00-06	2	17	completed
12	2026-07-16 09:15:00-06	2	16	completed
13	2026-07-17 09:15:00-06	2	5	completed
14	2026-07-20 09:15:00-06	4	3	completed
15	2026-07-21 09:15:00-06	2	2	completed
16	2026-07-22 09:15:00-06	16	2	completed
17	2026-07-23 09:15:00-06	5	20	completed
18	2026-07-24 09:15:00-06	12	12	completed
19	2026-08-03 09:15:00-06	22	3	completed
20	2026-08-03 11:15:00-06	2	2	completed
21	2026-08-04 09:15:00-06	3	1	completed
22	2026-08-04 11:15:00-06	3	3	completed
23	2026-08-05 09:15:00-06	10	10	completed
24	2026-08-05 11:15:00-06	4	19	completed
25	2026-08-06 09:15:00-06	4	11	completed
26	2026-08-07 09:15:00-06	14	1	completed
27	2026-08-10 09:15:00-06	15	8	completed
28	2026-08-11 09:15:00-06	16	9	completed
29	2026-08-12 09:15:00-06	13	13	completed
30	2026-08-13 09:15:00-06	19	12	completed
31	2026-08-14 09:15:00-06	3	18	completed
32	2026-08-17 09:15:00-06	22	15	completed
33	2026-08-18 09:15:00-06	8	5	completed
34	2026-08-19 09:15:00-06	14	14	completed
35	2026-08-20 09:15:00-06	19	18	completed
36	2026-08-21 09:15:00-06	1	1	completed
37	2026-08-24 09:15:00-06	3	5	completed
38	2026-08-25 09:15:00-06	9	2	completed
39	2026-08-26 09:15:00-06	5	5	completed
40	2026-08-27 09:15:00-06	7	20	completed
41	2026-08-28 09:15:00-06	1	1	completed
42	2026-08-31 09:15:00-06	3	2	completed
43	2026-09-01 09:15:00-06	14	7	completed
44	2026-09-01 11:15:00-06	13	6	completed
45	2026-09-02 09:15:00-06	9	5	completed
46	2026-09-02 11:15:00-06	11	11	completed
47	2026-09-03 09:15:00-06	19	19	completed
48	2026-09-03 11:15:00-06	16	15	completed
49	2026-09-04 09:15:00-06	6	6	completed
50	2026-09-04 11:15:00-06	17	8	completed
51	2026-09-07 09:15:00-06	2	1	completed
52	2026-09-07 11:15:00-06	3	3	completed
53	2026-09-08 09:15:00-06	17	17	completed
54	2026-09-08 11:15:00-06	20	20	completed
55	2026-09-09 09:15:00-06	1	1	completed
56	2026-09-09 11:15:00-06	1	16	completed
57	2026-09-10 09:15:00-06	3	3	completed
58	2026-09-10 11:15:00-06	3	3	completed
59	2026-09-11 09:15:00-06	1	1	completed
60	2026-09-11 11:15:00-06	18	11	completed
61	2026-09-14 09:15:00-06	8	1	completed
62	2026-09-14 11:15:00-06	4	1	completed
63	2026-09-15 09:15:00-06	10	16	completed
64	2026-09-15 11:15:00-06	1	2	completed
65	2026-09-16 09:15:00-06	1	5	completed
66	2026-09-17 09:15:00-06	20	13	completed
67	2026-09-18 09:15:00-06	11	4	completed
68	2026-09-21 09:15:00-06	18	18	completed
69	2026-09-22 09:15:00-06	9	9	completed
70	2026-09-23 09:15:00-06	11	4	completed
71	2026-09-24 09:15:00-06	2	2	completed
72	2026-09-25 09:15:00-06	21	14	completed
73	2026-09-14 15:30:00-06	23	1	cancelled
74	2026-09-15 15:30:00-06	24	2	cancelled
75	2026-09-16 15:30:00-06	3	3	cancelled
76	2026-09-17 15:30:00-06	4	4	cancelled
77	2026-09-18 15:30:00-06	5	5	cancelled
78	2026-09-19 15:30:00-06	6	6	cancelled
79	2026-09-20 15:30:00-06	7	7	no_show
80	2026-09-21 15:30:00-06	8	8	no_show
81	2026-09-22 15:30:00-06	9	9	no_show
82	2026-09-23 15:30:00-06	10	10	no_show
83	2026-10-01 10:00:00-06	23	1	scheduled
84	2026-10-02 10:00:00-06	24	2	scheduled
85	2026-10-05 10:00:00-06	1	3	scheduled
86	2026-10-06 10:00:00-06	2	4	scheduled
87	2026-10-07 10:00:00-06	5	5	scheduled
88	2026-10-08 10:00:00-06	8	6	scheduled
89	2026-10-09 10:00:00-06	12	7	scheduled
90	2026-10-12 10:00:00-06	16	8	scheduled
\.


--
-- Data for Name: bill; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.bill (bill_id, visit_id, amount, bill_date, status) FROM stdin;
1	1	160.00	2026-07-01	partially_paid
2	2	175.00	2026-07-02	paid
3	3	115.00	2026-07-03	paid
4	4	105.50	2026-07-06	paid
5	5	175.00	2026-07-07	paid
6	6	195.00	2026-07-08	unpaid
7	7	165.00	2026-07-09	partially_paid
8	8	155.00	2026-07-10	paid
9	9	120.50	2026-07-13	paid
10	10	215.00	2026-07-14	paid
11	11	215.00	2026-07-15	paid
12	12	220.50	2026-07-16	unpaid
13	13	175.00	2026-07-17	partially_paid
14	14	110.50	2026-07-20	paid
15	15	110.00	2026-07-21	paid
16	16	105.00	2026-07-22	paid
17	17	150.00	2026-07-23	paid
18	18	205.00	2026-07-24	unpaid
19	19	115.00	2026-08-03	partially_paid
20	20	100.00	2026-08-03	paid
21	21	85.00	2026-08-04	paid
22	22	100.00	2026-08-04	paid
23	23	165.50	2026-08-05	paid
24	24	180.00	2026-08-05	unpaid
25	25	170.00	2026-08-06	partially_paid
26	26	95.00	2026-08-07	paid
27	27	135.00	2026-08-10	paid
28	28	120.00	2026-08-11	paid
29	29	220.00	2026-08-12	paid
30	30	225.00	2026-08-13	unpaid
31	31	195.00	2026-08-14	partially_paid
32	32	190.00	2026-08-17	paid
33	33	190.00	2026-08-18	paid
34	34	190.50	2026-08-19	paid
35	35	200.00	2026-08-20	paid
36	36	105.50	2026-08-21	unpaid
37	37	185.50	2026-08-24	partially_paid
38	38	100.00	2026-08-25	paid
39	39	165.00	2026-08-26	paid
40	40	175.00	2026-08-27	paid
41	41	85.00	2026-08-28	paid
42	42	80.00	2026-08-31	unpaid
43	43	190.00	2026-09-01	partially_paid
44	44	170.50	2026-09-01	paid
45	45	175.00	2026-09-02	paid
46	46	150.50	2026-09-02	paid
47	47	200.00	2026-09-03	paid
48	48	195.00	2026-09-03	unpaid
49	49	170.50	2026-09-04	partially_paid
50	50	110.00	2026-09-04	paid
51	51	115.00	2026-09-07	paid
52	52	95.50	2026-09-07	paid
53	53	245.00	2026-09-08	paid
54	54	160.00	2026-09-08	unpaid
55	55	100.00	2026-09-09	partially_paid
56	56	215.00	2026-09-09	paid
57	57	85.00	2026-09-10	paid
58	58	100.00	2026-09-10	paid
59	59	110.00	2026-09-11	paid
60	60	160.00	2026-09-11	unpaid
61	61	90.00	2026-09-14	partially_paid
62	62	85.00	2026-09-14	paid
63	63	240.50	2026-09-15	paid
64	64	110.50	2026-09-15	paid
65	65	180.00	2026-09-16	paid
66	66	220.00	2026-09-17	unpaid
67	67	95.00	2026-09-18	partially_paid
68	68	205.00	2026-09-21	paid
69	69	125.00	2026-09-22	paid
70	70	100.00	2026-09-23	paid
71	71	115.00	2026-09-24	paid
72	72	200.50	2026-09-25	unpaid
\.


--
-- Data for Name: doctor; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.doctor (doctor_id, first_name, last_name, specialty, phone, email) FROM stdin;
1	Sarah	Mitchell	family_medicine	+1-403-555-0130	doctor01@example.invalid
2	David	Park	family_medicine	+1-403-555-0131	doctor02@example.invalid
3	Priya	Shah	family_medicine	+1-403-555-0132	doctor03@example.invalid
4	Michael	Reed	family_medicine	+1-403-555-0133	doctor04@example.invalid
5	Amina	Hassan	internal_medicine	+1-403-555-0134	doctor05@example.invalid
6	Robert	Chen	internal_medicine	+1-403-555-0135	doctor06@example.invalid
7	Elena	Rossi	internal_medicine	+1-403-555-0136	doctor07@example.invalid
8	Grace	Williams	pediatrics	+1-403-555-0137	doctor08@example.invalid
9	Omar	Khan	pediatrics	+1-403-555-0138	doctor09@example.invalid
10	Emily	Brooks	dermatology	+1-403-555-0139	doctor10@example.invalid
11	Daniel	Wu	dermatology	+1-403-555-0140	doctor11@example.invalid
12	Sofia	Alvarez	cardiology	+1-403-555-0141	doctor12@example.invalid
13	Andrew	Miller	cardiology	+1-403-555-0142	doctor13@example.invalid
14	Hannah	Cooper	orthopedics	+1-403-555-0143	doctor14@example.invalid
15	Kevin	Tran	orthopedics	+1-403-555-0144	doctor15@example.invalid
16	Leila	Farah	neurology	+1-403-555-0145	doctor16@example.invalid
17	Thomas	Evans	neurology	+1-403-555-0146	doctor17@example.invalid
18	Nina	Desai	endocrinology	+1-403-555-0147	doctor18@example.invalid
19	Marcus	Hill	psychiatry	+1-403-555-0148	doctor19@example.invalid
20	Julia	Bennett	ophthalmology	+1-403-555-0149	doctor20@example.invalid
\.


--
-- Data for Name: patient; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.patient (patient_id, first_name, last_name, email, gender, phone) FROM stdin;
1	Liam	Bennett	patient01@example.invalid	male	+1-403-555-0100
2	Olivia	Chen	patient02@example.invalid	female	+1-403-555-0101
3	Noah	Patel	patient03@example.invalid	male	+1-403-555-0102
4	Emma	Wilson	patient04@example.invalid	female	+1-403-555-0103
5	Ethan	Martin	patient05@example.invalid	male	+1-403-555-0104
6	Ava	Nguyen	patient06@example.invalid	female	+1-403-555-0105
7	Lucas	Ahmed	patient07@example.invalid	male	+1-403-555-0106
8	Mia	Thompson	patient08@example.invalid	female	+1-403-555-0107
9	Mason	Lee	patient09@example.invalid	male	+1-403-555-0108
10	Sophia	Garcia	patient10@example.invalid	female	+1-403-555-0109
11	James	O'Neil	\N	male	+1-403-555-0110
12	Isabella	Singh	patient12@example.invalid	female	+1-403-555-0111
13	Benjamin	Taylor	patient13@example.invalid	male	+1-403-555-0112
14	Charlotte	Brown	patient14@example.invalid	female	+1-403-555-0113
15	Henry	Kim	patient15@example.invalid	male	+1-403-555-0114
16	Amelia	Davis	patient16@example.invalid	female	+1-403-555-0115
17	Alex	Morgan	patient17@example.invalid	non_binary	+1-403-555-0116
18	Harper	Robinson	patient18@example.invalid	female	+1-403-555-0117
19	Daniel	Lopez	patient19@example.invalid	male	+1-403-555-0118
20	Evelyn	Clark	patient20@example.invalid	female	+1-403-555-0119
21	Samuel	Wright	patient21@example.invalid	male	+1-403-555-0120
22	Abigail	Scott	patient22@example.invalid	female	+1-403-555-0121
23	Jordan	Young	\N	prefer_not_to_say	+1-403-555-0122
24	Chloe	Walker	patient24@example.invalid	female	+1-403-555-0123
\.


--
-- Data for Name: payment; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.payment (payment_id, bill_id, amount_paid, payment_date, payment_method) FROM stdin;
1	1	64.00	2026-07-02	debit_card
2	2	78.75	2026-07-02	credit_card
3	3	51.75	2026-07-03	e_transfer
4	2	96.25	2026-07-04	e_transfer
5	3	63.25	2026-07-05	cash
6	4	105.50	2026-07-06	cash
7	5	175.00	2026-07-07	debit_card
8	7	66.00	2026-07-10	e_transfer
9	8	69.75	2026-07-10	cash
10	8	85.25	2026-07-12	debit_card
11	9	54.22	2026-07-13	debit_card
12	10	215.00	2026-07-14	credit_card
13	9	66.28	2026-07-15	credit_card
14	11	215.00	2026-07-15	e_transfer
15	13	70.00	2026-07-18	debit_card
16	14	49.72	2026-07-20	credit_card
17	15	49.50	2026-07-21	e_transfer
18	14	60.78	2026-07-22	e_transfer
19	16	105.00	2026-07-22	cash
20	15	60.50	2026-07-23	cash
21	17	150.00	2026-07-23	debit_card
22	20	45.00	2026-08-03	cash
23	19	46.00	2026-08-04	e_transfer
24	21	38.25	2026-08-04	debit_card
25	22	100.00	2026-08-04	credit_card
26	20	55.00	2026-08-05	debit_card
27	23	165.50	2026-08-05	e_transfer
28	21	46.75	2026-08-06	credit_card
29	25	68.00	2026-08-07	debit_card
30	26	42.75	2026-08-07	credit_card
31	26	52.25	2026-08-09	e_transfer
32	27	60.75	2026-08-10	e_transfer
33	28	120.00	2026-08-11	cash
34	27	74.25	2026-08-12	cash
35	29	220.00	2026-08-12	debit_card
36	31	78.00	2026-08-15	e_transfer
37	32	85.50	2026-08-17	cash
38	33	85.50	2026-08-18	debit_card
39	32	104.50	2026-08-19	debit_card
40	34	190.50	2026-08-19	credit_card
41	33	104.50	2026-08-20	credit_card
42	35	200.00	2026-08-20	e_transfer
43	37	74.20	2026-08-25	debit_card
44	38	45.00	2026-08-25	credit_card
45	39	74.25	2026-08-26	e_transfer
46	38	55.00	2026-08-27	e_transfer
47	40	175.00	2026-08-27	cash
48	39	90.75	2026-08-28	cash
49	41	85.00	2026-08-28	debit_card
50	44	76.72	2026-09-01	cash
51	43	76.00	2026-09-02	e_transfer
52	45	78.75	2026-09-02	debit_card
53	46	150.50	2026-09-02	credit_card
54	44	93.78	2026-09-03	debit_card
55	47	200.00	2026-09-03	e_transfer
56	45	96.25	2026-09-04	credit_card
57	50	49.50	2026-09-04	credit_card
58	49	68.20	2026-09-05	debit_card
59	50	60.50	2026-09-06	e_transfer
60	51	51.75	2026-09-07	e_transfer
61	52	95.50	2026-09-07	cash
62	53	245.00	2026-09-08	debit_card
63	51	63.25	2026-09-09	cash
64	56	96.75	2026-09-09	cash
65	55	40.00	2026-09-10	e_transfer
66	57	38.25	2026-09-10	debit_card
67	58	100.00	2026-09-10	credit_card
68	56	118.25	2026-09-11	debit_card
69	59	110.00	2026-09-11	e_transfer
70	57	46.75	2026-09-12	credit_card
71	62	38.25	2026-09-14	credit_card
72	61	36.00	2026-09-15	debit_card
73	63	108.22	2026-09-15	e_transfer
74	64	110.50	2026-09-15	cash
75	62	46.75	2026-09-16	e_transfer
76	65	180.00	2026-09-16	debit_card
77	63	132.28	2026-09-17	cash
78	67	38.00	2026-09-19	e_transfer
79	68	92.25	2026-09-21	cash
80	69	56.25	2026-09-22	debit_card
81	68	112.75	2026-09-23	debit_card
82	70	100.00	2026-09-23	credit_card
83	69	68.75	2026-09-24	credit_card
84	71	115.00	2026-09-24	e_transfer
\.


--
-- Data for Name: visit; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.visit (visit_id, appointment_id, visit_date, diagnosis, treatment) FROM stdin;
1	1	2026-07-01	Persistent fatigue	Initial assessment completed; laboratory review arranged
2	2	2026-07-02	Elevated cholesterol follow-up	Laboratory results reviewed; monitoring plan discussed
3	3	2026-07-03	Blood pressure follow-up	Home readings reviewed; follow-up booked
4	4	2026-07-06	Routine wellness assessment	Preventive screening discussed
5	5	2026-07-07	Persistent fatigue	Initial assessment completed; laboratory review arranged
6	6	2026-07-08	Knee pain assessment	Mobility assessed; physiotherapy referral discussed
7	7	2026-07-09	Persistent fatigue	Initial assessment completed; laboratory review arranged
8	8	2026-07-10	Contact dermatitis	Possible triggers reviewed; follow-up arranged
9	9	2026-07-13	Routine pediatric assessment	Growth record reviewed; follow-up discussed with guardian
10	10	2026-07-14	Migraine follow-up	Headache diary reviewed; follow-up arranged
11	11	2026-07-15	Migraine follow-up	Headache diary reviewed; follow-up arranged
12	12	2026-07-16	Migraine follow-up	Headache diary reviewed; follow-up arranged
13	13	2026-07-17	Persistent fatigue	Initial assessment completed; laboratory review arranged
14	14	2026-07-20	Blood pressure follow-up	Home readings reviewed; follow-up booked
15	15	2026-07-21	Routine wellness assessment	Preventive screening discussed
16	16	2026-07-22	Blood pressure follow-up	Home readings reviewed; follow-up booked
17	17	2026-07-23	Dry eye symptoms	Eye assessment completed; care plan reviewed
18	18	2026-07-24	Hypertension follow-up	Blood pressure log reviewed; specialist follow-up booked
19	19	2026-08-03	Blood pressure follow-up	Home readings reviewed; follow-up booked
20	20	2026-08-03	Routine wellness assessment	Preventive screening discussed
21	21	2026-08-04	Seasonal allergic rhinitis	Symptoms reviewed; follow-up arranged
22	22	2026-08-04	Blood pressure follow-up	Home readings reviewed; follow-up booked
23	23	2026-08-05	Contact dermatitis	Possible triggers reviewed; follow-up arranged
24	24	2026-08-05	Sleep difficulty assessment	Sleep history reviewed; follow-up discussed
25	25	2026-08-06	Contact dermatitis	Possible triggers reviewed; follow-up arranged
26	26	2026-08-07	Routine wellness assessment	Preventive screening discussed
27	27	2026-08-10	Eczema follow-up	Skin assessment completed; care plan reviewed with guardian
28	28	2026-08-11	Eczema follow-up	Skin assessment completed; care plan reviewed with guardian
29	29	2026-08-12	Hypertension follow-up	Blood pressure log reviewed; specialist follow-up booked
30	30	2026-08-13	Palpitations assessment	History reviewed; diagnostic testing arranged
31	31	2026-08-14	Thyroid follow-up	Laboratory results reviewed; monitoring appointment arranged
32	32	2026-08-17	Shoulder pain follow-up	Range of motion reviewed; rehabilitation plan discussed
33	33	2026-08-18	Elevated cholesterol follow-up	Laboratory results reviewed; monitoring plan discussed
34	34	2026-08-19	Knee pain assessment	Mobility assessed; physiotherapy referral discussed
35	35	2026-08-20	Thyroid follow-up	Laboratory results reviewed; monitoring appointment arranged
36	36	2026-08-21	Routine wellness assessment	Preventive screening discussed
37	37	2026-08-24	Elevated cholesterol follow-up	Laboratory results reviewed; monitoring plan discussed
38	38	2026-08-25	Routine wellness assessment	Preventive screening discussed
39	39	2026-08-26	Persistent fatigue	Initial assessment completed; laboratory review arranged
40	40	2026-08-27	Routine eye assessment	Vision reviewed; routine follow-up discussed
41	41	2026-08-28	Upper respiratory symptoms	Clinical assessment completed; review arranged
42	42	2026-08-31	Upper respiratory symptoms	Clinical assessment completed; review arranged
43	43	2026-09-01	Elevated cholesterol follow-up	Laboratory results reviewed; monitoring plan discussed
44	44	2026-09-01	Persistent fatigue	Initial assessment completed; laboratory review arranged
45	45	2026-09-02	Persistent fatigue	Initial assessment completed; laboratory review arranged
46	46	2026-09-02	Acne follow-up	Skin assessment completed; existing care plan reviewed
47	47	2026-09-03	Anxiety follow-up	Symptoms reviewed; counselling follow-up arranged
48	48	2026-09-03	Shoulder pain follow-up	Range of motion reviewed; rehabilitation plan discussed
49	49	2026-09-04	Persistent fatigue	Initial assessment completed; laboratory review arranged
50	50	2026-09-04	Routine pediatric assessment	Growth record reviewed; follow-up discussed with guardian
51	51	2026-09-07	Blood pressure follow-up	Home readings reviewed; follow-up booked
52	52	2026-09-07	Seasonal allergic rhinitis	Symptoms reviewed; follow-up arranged
53	53	2026-09-08	Intermittent tingling	Neurological assessment completed; testing arranged
54	54	2026-09-08	Routine eye assessment	Vision reviewed; routine follow-up discussed
55	55	2026-09-09	Routine wellness assessment	Preventive screening discussed
56	56	2026-09-09	Migraine follow-up	Headache diary reviewed; follow-up arranged
57	57	2026-09-10	Seasonal allergic rhinitis	Symptoms reviewed; follow-up arranged
58	58	2026-09-10	Blood pressure follow-up	Home readings reviewed; follow-up booked
59	59	2026-09-11	Routine wellness assessment	Preventive screening discussed
60	60	2026-09-11	Contact dermatitis	Possible triggers reviewed; follow-up arranged
61	61	2026-09-14	Seasonal allergic rhinitis	Symptoms reviewed; follow-up arranged
62	62	2026-09-14	Seasonal allergic rhinitis	Symptoms reviewed; follow-up arranged
63	63	2026-09-15	Intermittent tingling	Neurological assessment completed; testing arranged
64	64	2026-09-15	Blood pressure follow-up	Home readings reviewed; follow-up booked
65	65	2026-09-16	Elevated cholesterol follow-up	Laboratory results reviewed; monitoring plan discussed
66	66	2026-09-17	Hypertension follow-up	Blood pressure log reviewed; specialist follow-up booked
67	67	2026-09-18	Routine wellness assessment	Preventive screening discussed
68	68	2026-09-21	Diabetes follow-up	Monitoring records reviewed; specialist follow-up arranged
69	69	2026-09-22	Eczema follow-up	Skin assessment completed; care plan reviewed with guardian
70	70	2026-09-23	Routine wellness assessment	Preventive screening discussed
71	71	2026-09-24	Blood pressure follow-up	Home readings reviewed; follow-up booked
72	72	2026-09-25	Shoulder pain follow-up	Range of motion reviewed; rehabilitation plan discussed
\.


--
-- Name: appointment_appointment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.appointment_appointment_id_seq', 91, false);


--
-- Name: bill_bill_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.bill_bill_id_seq', 73, false);


--
-- Name: doctor_doctor_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.doctor_doctor_id_seq', 21, false);


--
-- Name: patient_patient_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.patient_patient_id_seq', 25, false);


--
-- Name: payment_payment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.payment_payment_id_seq', 85, false);


--
-- Name: visit_visit_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.visit_visit_id_seq', 73, false);


--
-- Name: appointment appointment_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.appointment
    ADD CONSTRAINT appointment_pkey PRIMARY KEY (appointment_id);


--
-- Name: bill bill_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bill
    ADD CONSTRAINT bill_pkey PRIMARY KEY (bill_id);


--
-- Name: bill bill_visit_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bill
    ADD CONSTRAINT bill_visit_id_key UNIQUE (visit_id);


--
-- Name: doctor doctor_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.doctor
    ADD CONSTRAINT doctor_email_key UNIQUE (email);


--
-- Name: doctor doctor_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.doctor
    ADD CONSTRAINT doctor_pkey PRIMARY KEY (doctor_id);


--
-- Name: patient patient_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.patient
    ADD CONSTRAINT patient_pkey PRIMARY KEY (patient_id);


--
-- Name: payment payment_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payment
    ADD CONSTRAINT payment_pkey PRIMARY KEY (payment_id);


--
-- Name: visit visit_appointment_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.visit
    ADD CONSTRAINT visit_appointment_id_key UNIQUE (appointment_id);


--
-- Name: visit visit_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.visit
    ADD CONSTRAINT visit_pkey PRIMARY KEY (visit_id);


--
-- Name: appointment_doctor_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX appointment_doctor_id_idx ON public.appointment USING btree (doctor_id);


--
-- Name: appointment_patient_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX appointment_patient_id_idx ON public.appointment USING btree (patient_id);


--
-- Name: bill_bill_date_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX bill_bill_date_idx ON public.bill USING btree (bill_date);


--
-- Name: payment_bill_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX payment_bill_id_idx ON public.payment USING btree (bill_id);


--
-- Name: visit_visit_date_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX visit_visit_date_idx ON public.visit USING btree (visit_date);


--
-- Name: appointment appointment_doctor_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.appointment
    ADD CONSTRAINT appointment_doctor_id_fkey FOREIGN KEY (doctor_id) REFERENCES public.doctor(doctor_id);


--
-- Name: appointment appointment_patient_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.appointment
    ADD CONSTRAINT appointment_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patient(patient_id);


--
-- Name: bill bill_visit_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bill
    ADD CONSTRAINT bill_visit_id_fkey FOREIGN KEY (visit_id) REFERENCES public.visit(visit_id);


--
-- Name: payment payment_bill_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payment
    ADD CONSTRAINT payment_bill_id_fkey FOREIGN KEY (bill_id) REFERENCES public.bill(bill_id);


--
-- Name: visit visit_appointment_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.visit
    ADD CONSTRAINT visit_appointment_id_fkey FOREIGN KEY (appointment_id) REFERENCES public.appointment(appointment_id);


--
-- PostgreSQL database dump complete
--

\unrestrict 4PHWJWaB9AhX9ycsKHRehZy2cPXaBBaeBNNSkeSRb4lurwYRYluKCsRhQwFgvNk

