-- Medical clinic: PostgreSQL schema matching the final six-table EERD.
-- Connect to sait_medical_clinic and run once; these tables must not exist in public.
-- Names are lowercase; SQL keywords are uppercase.
-- The medical_history view is defined separately in views.sql.

BEGIN;

CREATE TABLE public.patient (
    patient_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name TEXT NOT NULL CHECK (btrim(first_name) <> ''),
    last_name TEXT NOT NULL CHECK (btrim(last_name) <> ''),
    email TEXT,
    gender TEXT,
    phone TEXT
);

CREATE TABLE public.doctor (
    doctor_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name TEXT NOT NULL CHECK (btrim(first_name) <> ''),
    last_name TEXT NOT NULL CHECK (btrim(last_name) <> ''),
    specialty TEXT NOT NULL CHECK (btrim(specialty) <> ''),
    phone TEXT,
    email TEXT NOT NULL UNIQUE
);

CREATE TABLE public.appointment (
    appointment_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_dt TIMESTAMP WITH TIME ZONE NOT NULL,
    patient_id INTEGER NOT NULL REFERENCES public.patient(patient_id),
    doctor_id INTEGER NOT NULL REFERENCES public.doctor(doctor_id),
    status TEXT NOT NULL DEFAULT 'scheduled',
    CONSTRAINT appointment_status_check
        CHECK (status IN ('scheduled', 'completed', 'cancelled', 'no_show'))
);

CREATE TABLE public.visit (
    visit_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_id INTEGER NOT NULL UNIQUE
        REFERENCES public.appointment(appointment_id),
    visit_date DATE NOT NULL,
    diagnosis TEXT NOT NULL CHECK (btrim(diagnosis) <> ''),
    treatment TEXT NOT NULL CHECK (btrim(treatment) <> '')
);

CREATE TABLE public.bill (
    bill_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    visit_id INTEGER NOT NULL UNIQUE REFERENCES public.visit(visit_id),
    amount NUMERIC(10, 2) NOT NULL,
    bill_date DATE NOT NULL,
    status TEXT NOT NULL DEFAULT 'unpaid',
    CONSTRAINT bill_amount_check
        CHECK (amount BETWEEN 0.01 AND 99999999.99),
    CONSTRAINT bill_status_check
        CHECK (status IN ('unpaid', 'partially_paid', 'paid'))
);

CREATE TABLE public.payment (
    payment_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bill_id INTEGER NOT NULL REFERENCES public.bill(bill_id),
    amount_paid NUMERIC(10, 2) NOT NULL,
    payment_date DATE NOT NULL,
    payment_method TEXT NOT NULL,
    CONSTRAINT payment_amount_check
        CHECK (amount_paid BETWEEN 0.01 AND 99999999.99),
    CONSTRAINT payment_method_check
        CHECK (payment_method IN ('cash', 'debit_card', 'credit_card', 'e_transfer'))
);

-- Foreign-key indexes; UNIQUE already indexes visit.appointment_id and bill.visit_id.
CREATE INDEX appointment_patient_id_idx ON public.appointment(patient_id);
CREATE INDEX appointment_doctor_id_idx ON public.appointment(doctor_id);
CREATE INDEX payment_bill_id_idx ON public.payment(bill_id);
CREATE INDEX visit_visit_date_idx ON public.visit(visit_date);
CREATE INDEX bill_bill_date_idx ON public.bill(bill_date);

-- Application/transaction responsibilities (audited by verify.sql):
-- 1. Mark the appointment completed and create its visit and bill together.
-- 2. Only completed appointments have visits; every visit has exactly one bill.
-- 3. Record payments to the clinic, prevent overpayment, and update bill.status.
-- 4. Keep appointment/visit/bill/payment dates in chronological order.
-- FK + UNIQUE enforce at most one child, not the mandatory existence of a child.
-- These cross-table rules are deliberately not claimed as CHECK constraints.

COMMIT;
